"""empty message

Revision ID: 1f9c07777e0f
Revises: 2da24196ba52
Create Date: 2015-09-10 22:34:08.913683

"""

# revision identifiers, used by Alembic.
revision = '1f9c07777e0f'
down_revision = '2da24196ba52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    ### end Alembic commands ###
